name: Build data-aggregation

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        working-directory: ./data-aggregation
        run: ./gradlew build
  build_docker_server:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        working-directory: data-aggregation
        run: docker build -t energydrinkprices/data-aggregation:latest .

      - name: Push Docker image
        working-directory: data-aggregation
        run: docker push energydrinkprices/data-aggregation:latest
