name: Build user interface

on: push

jobs:
  build_docker_user-interface:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}/user-interface
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/user-interface:latest
