name: Test java

on: push

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test server
        working-directory: ./server
        run: ./gradlew test -i
      - name: Test data-aggregation
        working-directory: ./data-aggregation
        run: ./gradlew test -i
